###
# List of methods/modules and their dependencies:
###
modules:
    - name: array_ops
    - name: conjugate_gradient
      depends: ['array_ops']
    - name: svd_mf
    #- name: linalg
    #- name: utilities
    #  depends: ['linalg']
    #- name: regress
    #  depends: ['utilities']
    #
